### PR TITLE
Basic implementation of mapping iterator

### PR DESCRIPTION
**Pull request by msurkovsky**
Here is a basic implementation of mapping iterator. It can be used for some test, before the problem with indexing of elements will be solved.

### CODE REVIEW

**Comment by spirali** [comment]
It is good to have also general implementation of mapping; it can be used for non-indexable types. Hence I have no problem to merge it as it is. However I have some comments for tests:

- Use itertools.permutations to make tests more readable
- Test also more complex types than integer
- Test corner cases (like empty mapping)
- Test propagation of free variables (e.g. domain is Range(x))

**Comment by msurkovsky** [comment]
Yes, I will extend the test. I want do it after playimg with mapping during the work on"synthesis" example. As for the itertools I'm aware of it, but I had some problems with using it. Neverthless, I'm convinced it's my problem and I have to read the docs more carefully :-)

**Comment by spirali** [comment]
For the first time, I have reviewed the code in haste, now I see some other issues:

- I do not understand the machinery in computePermutation, what it exactly does?
- MappingIterator::reset() calls MappingReset
- do not use stdout to report errors (use stderr)
- do not use exceptions in places that can be easily done without it
- do not use camelCase for method naming (computePermutation)
- I think that method "compute_combination_number" is ill-named, since it does not compute a combination number

**Comment by msurkovsky** [comment]
Most of the things are in an older version of implementation. I wanted to preserve it only because it is a bit different attempt and I wasn't sure whether or not I would have wanted to return back to it. Nevertheless, I see some other issues in the last version. But I will work on it after your answer on my reported issue.

**Comment by msurkovsky** [comment]
I think you can close/cancel this pull request.

**Pull request closed without merging**
